# Generated by Django 4.2.10 on 2024-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_historicaluserprofile_online_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
model_name = 'historicaluserprofile'
name = 'online_status'
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
model_name='userprofile',
            name='online_status',
            field=models.BooleanField(default=False, null=False, blank=False),
        ),
    ]
