# Generated by Django 4.2.10 on 2024-02-27 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

try:
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
except ImportError as e:
    print(f"Error importing dependencies: {e}")
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='program_administrator_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='program_administrator_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
