# Generated by Django 4.2.10 on 2024-04-08 18:59

from django.conf import settings
from django.db import migrations, models
from django.db import models
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = []
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programuser',
            name='is_mentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programuser',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='account_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='program',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_admin', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_administrator_id',
try:
    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_admin', to=settings.AUTH_USER_MODEL)
except Exception as e:
    print(f"An error occurred: {e}")

try:
            name='program',
        ),
        migrations.AddField(
            model_name='programuser',
            name='program',
            field=models.ManyToManyField(related_name='program_user', to='programs.program'),
        ),
    ]
