# Generated by Django 4.2.10 on 2024-04-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('programs', '0003_programuser_is_mentee_programuser_is_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meeting_link', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('session_rating', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Bad'), (1, 'Very Bad')])),
                ('session_completed', models.BooleanField(default=False)),
                ('mentor_feedback', models.CharField(max_length=250)),
                ('mentee_feedback', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched', models.BooleanField(default=False)),
                ('mentee_id', models.ManyToManyField(blank=True, null=True, related_name='mentee', to='programs.programuser')),
                ('mentor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='programs.programuser')),
                ('moderator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='programs.programuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_owner', to='accounts.accountuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
