# Generated by Django 4.2.10 on 2024-04-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_session_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='mentee_id',
            field=models.ManyToManyField(related_name='mentee', to='programs.programuser'),
        ),
        migrations.AlterField(
            model_name='match',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='programs.programuser'),
        ),
    ]
