# Generated by Django 4.2.10 on 2024-04-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_alter_match_mentee_id_alter_match_mentor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='moderator_id',
        ),
        migrations.AddField(
            model_name='match',
            name='moderator_id',
            field=models.ManyToManyField(null=True, related_name='moderator', to='programs.programuser'),
        ),
    ]
