# Generated by Django 4.2.10 on 2024-04-24 14:23

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = []

    def __init__(self, name):
        super().__init__(name=name)

def apply(self, project_state, schema_editor, collect_sql=False):
    try:
        operations = [
            ('programs', '0006_remove_match_moderator_id_match_moderator_id'),
            # Add more operations here
        ]
        migrations.AlterField(
            model_name='match',
            name='moderator_id',
            field=models.ManyToManyField(blank=True, related_name='moderator', to='programs.programuser'),
        ),
    ]
