# Generated by Django 4.2.10 on 2024-04-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
('chat', '0007_userchat_chat_room_id_alter_chatroom_member'),
('programs', '0007_alter_match_moderator_id'),
operations = [
    migrations.AddField(
            model_name='match',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
    ]
