# Generated by Django 4.2.10 on 2024-03-21 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roomId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(default='DM', max_length=10)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='chatmessagefile',
            name='chat_message_id',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='chat_room_id',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userchatmessage',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='send_by_user_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='text',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessageFile',
        ),
        migrations.DeleteModel(
            name='UserChat',
        ),
        migrations.DeleteModel(
            name='UserChatMessage',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatroom'),
        ),
    ]
