# Generated by Django 4.2.10 on 2024-04-03 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_userchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(blank=True, choices=[('DM', 'Direct Message'), ('Group', 'Group')], max_length=10, null=True),
        ),
    ]
