# Generated by Django 4.2.10 on 2024-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

try:
    dependencies = [
        ('chat', '0005_remove_chatroom_created_at_and_more'),
    ]
except Exception as e:
    print(f"Error: {e}")
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
