# Generated by Django 4.2.10 on 2024-04-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_match_moderator_id'),
('chat', '0006_userchat_text'),
operations = [
        migrations.AddField(
            model_name='userchat',
name = 'chat_room_id'
field = models.ForeignKey(
    null=True,
    on_delete=django.db.models.deletion.CASCADE,
    to='chat.chatroom',
)
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='chat_members', to='programs.programuser'),
        ),
    ]
